default: &default
  adapter: postgresql
  encoding: unicode
  host: '0.0.0.0'
  port: 55001
  username: 'postgres'
  password: 'postgrespw'
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: reactrails_development

test:
  <<: *default
  database: reactrails_test

production:
  <<: *default
  database: reactrails_production
  username: reactrails
  password: <%= ENV["REACTRAILS_DATABASE_PASSWORD"] %>
